// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CardGrid.tsx": () => import("../components/mockups/CardGrid.tsx"),
  "./components/mockups/Dashboard.tsx": () => import("../components/mockups/Dashboard.tsx"),
  "./components/mockups/PricingTable.tsx": () => import("../components/mockups/PricingTable.tsx")
};
